apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: APP_NAME
  namespace: PROJECT_NAME
  annotations:
    cert-manager.io/cluster-issuer: "mkcert-cluster-issuer"
    jaeger-sampler-param: 1
